#ifndef EQUIPOGRAPH_LIB_GLOBAL_H
#define EQUIPOGRAPH_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EQUIPOGRAPH_LIB_LIBRARY)
#  define EQUIPOGRAPH_LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EQUIPOGRAPH_LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EQUIPOGRAPH_LIB_GLOBAL_H
